const CACHED_AUTH = [
    {
        email_address: "test2@gmail.com",
        ticket_number: "2",
        is_couple: true
    },
    {
        email_address: "test@gmail.com",
        ticket_number: "1"
    },
    {
        email_address: "humphrey.akampumuza@gmail.com",
        ticket_number: "6716921"
    },
    { email_address: "yvetteninku@gmail.com", ticket_number: "6773158" },
    { email_address: "obucexec@gmail.com", ticket_number: "6773176" },
    { email_address: "obucexec@gmail.com", ticket_number: "6773177" },
    { email_address: "zoora.elton@gmail.com", ticket_number: "6783063" },
    { email_address: "sharonabiwemba@gmail.com", ticket_number: "6787946" },
    { email_address: "rkirungi20@gmail.com", ticket_number: "6789591" },
    { email_address: "jmssseggane@gmail.com", ticket_number: "6790452" },
    { email_address: "settuba.joseph@gmail.com", ticket_number: "6795887" },
    { email_address: "chodolists@gmail.com", ticket_number: "6795903" },
    { email_address: "phillipkiku577@gmail.com", ticket_number: "6796931" },
    { email_address: "marylnamutuhaire42@gmail.com", ticket_number: "6801785" },
    { email_address: "treasure.bujjingo@gmail.com", ticket_number: "6811211" },
    { email_address: "mutyabashadia@gmail.com", ticket_number: "6844503" },
    { email_address: "joymeb75@gmail.com", ticket_number: "6848355" },
    { email_address: "steven.kasulee@gmail.com", ticket_number: "6881233" },
    { email_address: "wab14dav@gmail.com", ticket_number: "6881319" },
    { email_address: "edgarwilliams234@gmail.com", ticket_number: "6883647" },
    { email_address: "monevanessa5@gmail.com", ticket_number: "6883654" },
    { email_address: "Katojacob113@gmail.com", ticket_number: "6887811" },
    { email_address: "danimwesi@gmail.com", ticket_number: "6895632" },
    { email_address: "tandekamutebi@gmail.com", ticket_number: "6895662" },
    { email_address: "kmkmatts@gmail.com", ticket_number: "6895684" },
    { email_address: "ilegofrancis04@gmail.com", ticket_number: "6900368" },
    { email_address: "kabamic@gmail.com", ticket_number: "6958896" },
    { email_address: "sebakkam@hotmail.com", ticket_number: "6967191" },
    { email_address: "dorkyqueen921@gmail.com", ticket_number: "6973907" },
    { email_address: "lauraaudrie@gmail.com", ticket_number: "6990685" },
    { email_address: "mps1401@gmail.com", ticket_number: "6990716" },
    { email_address: "kkchris34@gmail.com", ticket_number: "6990756" },
    { email_address: "jennykamaliza@gmail.com", ticket_number: "6990818" },
    { email_address: "dorisdorcus999@gmail.com", ticket_number: "6995559" },
    { email_address: "ruthevanzmirembe@gmail.com", ticket_number: "6995624" },
    { email_address: "charlotec28@gmail.com", ticket_number: "6995946" },
    { email_address: "ssuunae@gmail.com", ticket_number: "7029397" },
    { email_address: "parnetia@gmail.com", ticket_number: "7043903" },
    { email_address: "josephkayaye@gmail.com", ticket_number: "7045091" },
    { email_address: "davi.mayan@gmail.com", ticket_number: "7047425" },
    { email_address: "pheonahnamakula@gmail.com", ticket_number: "7050524" },
    { email_address: "kayemba17@gmail.com", ticket_number: "7052836" },
    { email_address: "matovuphilip@gmail.com", ticket_number: "7058962" },
    { email_address: "walusimbiedmund88@gmail.com", ticket_number: "7087630" },
    { email_address: "luswatac@aol.com", ticket_number: "7124803" },
    { email_address: "ebkasirye@gmail.com", ticket_number: "7124818" },
    { email_address: "ckmulimba@gmail.com", ticket_number: "7124826" },
    { email_address: "jrskatoug@gmail.com", ticket_number: "7137101" },
    { email_address: "warrenkahigiriza@gmail.com", ticket_number: "7152186" },
    { email_address: "jmssseggane@gmail.com", ticket_number: "7166303" }
];
module.exports.CACHED_AUTH = CACHED_AUTH;
